import 'package:get/get_navigation/src/root/internacionalization.dart';

class Strings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'app_title': 'OTMS 2.0',
          'need_help': "Need Help?",
          'create_new_account': "Create new account",
          'create_company': "Create Company",
          'log_in': 'Log In',
          'log_in_note1': 'What\'s your mobile\nnumber?',
          'log_in_note2': 'One number. Zero hassle. Instant login.',
          'do_not_have_an_account': 'Don\'t have an account?',
          'continue': "Continue",
          'enter_verification_code': "Enter Verification Code",
          'verification_code_sent_note':
              "We\'ve sent a 4-digit code to\nyour phone",
          'resend_code_in': "Resend code in",
          'did_not_get_the_code': "Didn't get the code?",
          'resend_now': "Resend Now",
          'sign_up_free_and_start_using_otm_system':
              'Signup free and start\nusing OTM System',
          'sign_up': 'Sign Up',
          'login': 'Login',
          'required_field': 'Required Field',
          'phone': 'Phone',
          'phone_number': 'Phone Number',
          'email': 'Email',
          'try_again': "Try Again",
          'no_internet': "Please Check Your Internet Connection!",
          'verify_otp': "Verify OTP",
          'verify_otp_hint1':
              "Enter the four-digit code that you were sent over mobile SMS.",
          'click_on_': "Click On ",
          'resend_': "Resend,",
          'otm_received_note': " if you do not receive after 2 minutes",
          'submit': "Submit",
          'enter_otp': "Enter OTP",
          'otp_resend_success_message': "Otp resend",
          'home': "Home",
          'profile': "Profile",
          'more': "More",
          'next': "Next",
          'first_name': "First Name",
          'last_name': "Last Name",
          'upload_photo_note_sign_up':
              "Upload your photo so that your team\nmate can recognize you",
          'upload_photo_capital': "UPLOAD PHOTO",
          'hint_upload_user_image': "Preferred Image Size: Square",
          'register': "Register",
          'error_phone_number_contain_10_digits':
              "Phone number must contain 10 digits",
          'error_phone_number_start_with_zero': "Phone number not start with 0",
          'error_phone_number_already_exist': "Phone Number already exists",
          'your_weekly_score_is': "Your weekly score is ",
          'analytics': "Analytics",
          'today_summery': "Today\'s Summery",
          'location_updates': "Location Updates",
          'next_updates': "Next Updates",
          'scheduled_break': "Scheduled Break",
          'empty_data_message': "No data found",
          'select_phone_extension': "Select phone extension",
          'search': "Search",
          'logout': "Logout",
          'logout_msg': "Are you sure you want to logout?",
          'yes': "Yes",
          'no': "No",
          'skip': "Skip",
          'close': "Close",
          'create_or_join_company': "Create or join\ncompany",
          'create_new_company': "Create new company",
          'join_a_company': "Join a company",
          'join_company': "Join Company",
          'select_company': "Select Company",
          'or': "Or",
          'add_company_code': "Add company code",
          'company_access_code': "Company Access Code",
          'enter_company_code_note':
              "Please enter the 4-digit code\nprovided by your company to join",
          'company_request_approved_note':
              "We will inform you as soon as your request to join the company has been approved.",
          'select_your_role': "Select your role",
          'whats_your_company_details': 'What\'s your company\ndetails?',
          'enter_valid_email_address': "Enter a valid email address",
          'business_email': "Business Email",
          'how_many_users_Are_on_your_team':
              "How many users are\non your team?",
          // '': "",
          // '': "",
          'do_it_later': "Do it later",
          'empty_company_list': "No company found",
          'are_you_sure_you_want_to_join': "Are you sure you want to join?",
          'please_enter_company_code': "Please enter company code",
          'please_select_trade': "Please select trade",
          'select_trade': "Select Trade",
          'empty_trade_list': "No trade found",
          'scan_barcode_note':
              "Place a barcode inside the viewfinder rectangle to scan it.",
          'error_invalid_qr_code_via_id_card_scan':
              "Invalid QR code , Please scan valid ID card",
          'company_details': "Company Details",
          'upload_photo': "Upload Photo",
          'preferred_company_logo_size': "Preferred image size: 600px X 250px.",
          'company_name': "Company Name",
          'head_office_location': "Head office location",
          'currency': "Currency",
          'select_currency': "Select Currency",
          'empty_currency_list': "No currency found",
          'dashboard': "Dashboard",
          'exit_warning': "Press Back Button Again to Exit.",
          'login_with_otp': "Login with OTP",
          'select_photo_from_': "Select Photo From:",
          'camera': "Camera",
          'gallery': "Gallery",
          'edit_photo': "Edit Photo",
          'empty_image_selection': "Please select image",
          'ERR103': "Phone Number already exists",
          'start_work': "Start Work",
          'continue_yesterdays_work': "Continue Yesterday's Work",
          'timesheet': "Timesheet",
          'requests': "Requests",
          'team': "Team",
          'select_project': "Select Project",
          'all_projects': "All Projects",
          'select_shift': "Select Shift",
          'all_shifts': "All Shifts",
          'work_time_on': "Work time on",
          'total_work_hour_today': "Total work hour today",
          'stop_work': "Stop Work",
          'my_day_log': "My day log",
          'check_in_addresses': "Check-in Addresses",
          'switch_project': "Switch Project",
          'check_in_': "Check-in",
          'check_out_': "Check-Out",
          'select_address': "Select Address",
          'ready_to_start_work': "Ready to start work",
          'in_progress': "In progress",
          'completed': "Completed",
          'status': "Status",
          'sort_by_': "Sort By:",
          'filter_by_': "Filter By:",
          'search_by_address_or_postcode': "Search by address or postcode",
          'details_of_work': "Detail of work",
          'type_of_work': "Type of work",
          'description': "Description",
          'photos_before': "Photos Before",
          'photos_after': "Photos After",
          'save': "Save",
          'shift_summery': "Shift Summary",
          'total_hours_': "Total hours:",
          'door_installation': "Door Installation",
          'add_a_note': "Add a Note",
          'confirm_time': "Confirm Time",
          'edit_entry': "Edit Entry",
          'submit_for_approval': "Submit for Approval",
          'enter_your_note_here': "Enter your note here...",
          // '': "",
          // '': "",
          // '': "",
          // '': "",
          // '': "",
          // '': "",
          // '': "",
          // '': "",
          // '': "",
          // '': "",
          // '': "",
          // '': "",
        },
        'hi_IN': {'login': 'Login'}
      };
}
