import 'package:get/get_navigation/src/root/internacionalization.dart';

class Strings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'app_title': 'Belcka',
          'first_screen_welcome_title': 'Welcome to Belcka',
          'first_screen_note':
              'Create. Connect. Conquer — launch your\ncompany or join your team now.',
          // '': '',
          // '': '',
          'need_help': "Need Help?",
          'create_new_account': "Create new account",
          'create_company': "Create Company",
          'log_in': 'Log In',
          'log_in_note1': 'What\'s your mobile\nnumber?',
          'log_in_note2': 'One number. Zero hassle. Instant login.',
          'do_not_have_an_account': 'Don\'t have an account?',
          'continue': "Continue",
          'finish': "Finish",
          'enter_verification_code': "Enter Verification Code",
          'verification_code_sent_note':
              "We\'ve sent a 6-digit code to\nyour phone",
          'resend_code_in': "Resend code in",
          'did_not_get_the_code': "Didn't get the code?",
          'resend_now': "Resend Now",
          'sign_up_free_and_start_using_otm_system':
              'Signup free and start\nusing Belcka',
          'sign_up': 'Sign Up',
          'login': 'Login',
          'required_field': 'Required Field',
          'phone': 'Phone',
          'phone_number': 'Phone Number',
          'email': 'Email',
          'try_again': "Try Again",
          'no_internet': "Please Check Your Internet Connection!",
          'no_internet_text': "No Internet",
          'verify_otp': "Verify OTP",
          'verify_otp_hint1':
              "Enter the four-digit code that you were sent over mobile SMS.",
          'click_on_': "Click On ",
          'resend_': "Resend,",
          'otm_received_note': " if you do not receive after 2 minutes",
          'submit': "Submit",
          'enter_otp': "Enter OTP",
          'otp_resend_success_message': "Otp resend",
          'home': "Home",
          'profile': "Profile",
          'more': "More",
          'next': "Next",
          'first_name': "First Name",
          'last_name': "Last Name",
          'middle_name': "Middle Name",
          'upload_photo_note_sign_up':
              "Upload your photo so that your team\nmate can recognize you",
          'upload_photo_capital': "UPLOAD PHOTO",
          'hint_upload_user_image': "Preferred Image Size: Square",
          'register': "Register",
          'error_phone_number_contain_10_digits':
              "Phone number must contain 10 digits",
          'error_phone_number_start_with_zero': "Phone number not start with 0",
          'error_phone_number_already_exist': "Phone Number already exists",
          'your_weekly_score_is': "Your weekly score is ",
          'analytics': "Analytics",
          'today_summery': "Today\'s Summery",
          'location_updates': "Location Updates",
          'next_updates': "Next Updates",
          'scheduled_break': "Scheduled Break",
          'empty_data_message': "No data found",
          'search': "Search",
          'logout': "Logout",
          'logout_msg': "Are you sure you want to logout?",
          'yes': "Yes",
          'no': "No",
          'skip': "Skip",
          'close': "Close",
          'create_or_join_company': "Create or join\ncompany",
          'create_new_company': "Create new company",
          'join_a_company': "Join a company",
          'join_company': "Join Company",
          'select_company': "Select Company",
          'or': "Or",
          'add_company_code': "Add company code",
          'company_access_code': "Company Access Code",
          'enter_company_code_note':
              "Please enter the 6-digit code\nprovided by your company to join",
          'company_request_approved_note':
              "We will inform you as soon as your request to join the company has been approved.",
          'select_your_trade': "Select your trade",
          'whats_your_company_details': 'What\'s your company\ndetails?',
          'enter_valid_email_address': "Enter a valid email address",
          'business_email': "Business Email",
          'how_many_users_Are_on_your_team':
              "How many users are\non your team?",
          'which_field_best_describe_your_business':
              "Which field best\ndescribes your business?",
          'business_field_info_note1': "Pick the tools your team\nneeds.",
          'business_field_info_note2':
              "Customize your workspace by selecting\nthe features you’ll use daily",
          'operations': "Operations",
          // '': "",
          'do_it_later': "Do it later",
          'empty_company_list': "No company found",
          'are_you_sure_you_want_to_join': "Are you sure you want to join?",
          'please_enter_company_code': "Please enter company code",
          'please_select_trade': "Please select trade",
          'please_select_image': "Please select image",
          'select_trade': "Select Trade",
          'empty_trade_list': "No trade found",
          'scan_barcode_note':
              "Place a barcode inside the viewfinder rectangle to scan it.",
          'error_invalid_qr_code_via_id_card_scan':
              "Invalid QR code , Please scan valid ID card",
          'company_details': "Company Details",
          'upload_photo': "Upload Photo",
          'preferred_company_logo_size': "Preferred image size: 600px X 250px.",
          'company_name': "Company Name",
          'head_office_location': "Head office location",
          'currency': "Currency",
          'select_currency': "Select Currency",
          'empty_currency_list': "No currency found",
          'dashboard': "Dashboard",
          'exit_warning': "Press Back Button Again to Exit.",
          'login_with_otp': "Login with OTP",
          'select_photo_from_': "Select Photo From:",
          'camera': "Camera",
          'gallery': "Gallery",
          'edit_photo': "Edit Photo",
          'empty_image_selection': "Please select image",
          'ERR103': "Phone Number already exists",
          'start_work': "Start Work",
          'continue_yesterdays_work': "Continue Yesterday's Work",
          'timesheet': "Timesheet",
          'requests': "Requests",
          'team': "Team",
          'select_project': "Select Project",
          'all_projects': "All Projects",
          'select_shift': "Select Shift",
          'all_shifts': "All Shifts",
          'work_time_on': "Work time on",
          'break_time_on': "Break time on",
          'total_work_hours_today': "Total work hours today",
          'stop_shift': "Stop Shift",
          'my_day_log': "My day log",
          'check_in_addresses': "Check-in Addresses",
          'switch_project': "Switch Project",
          'check_in_': "Check-In",
          'check_out_': "Check-Out",
          'select_address': "Select Address",
          'ready_to_start_work': "Ready to start work",
          'in_progress': "In progress",
          'completed': "Completed",
          'status': "Status",
          'sort_by_': "Sort By:",
          'filter_by_': "Filter By:",
          'search_by_address_or_postcode': "Search by address or postcode",
          'details_of_work': "Detail of work",
          'type_of_work': "Type of work",
          'description': "Description",
          'photos_before': "Photos Before",
          'photos_after': "Photos After",
          'save': "Save",
          'shift_summery': "Shift Summary",
          'total_hours': "Total Hours",
          'total_amount': "Total Amount",
          'rejected_hours': "Rejected Hours",
          'approved_hours': "Approved Hours",
          'door_installation': "Door Installation",
          'add_a_note': "Add a Note",
          'confirm_time': "Confirm Time",
          'edit_entry': "Edit Entry",
          'submit_for_approval': "Submit for Approval",
          'enter_your_note_here': "Enter your note here...",
          'reload': "Reload",
          'confirm': "Confirm",
          'please_select_company_logo': "Please select company logo",
          'country_code': "Country Code",
          'select_country_code': "Select country code",
          'widget': "Widget",
          'notification': "Notification",
          'notifications': "Notifications",
          'notification_settings': "Notification Settings",
          'settings': "Settings",
          'trades': "Trades",
          'blank': "Blank",
          'user_permissions': "User Permissions",
          'widgets': "widgets",
          'company_permissions': "Company Permissions",
          'permissions': "Permissions",
          'company_code': "Company Code",
          'company_admin': "Company Admin",
          'company_address': "Company Address",
          'company_email_address': "Company email address",
          'company_website': "Company Website",
          'company_description': "Company Description",
          'registration_number': "Registration Number",
          'vat_number': "VAT Number",
          'company_established_Date': "Company established date",
          'main_contracts': "Main Contracts",
          'working_hours': "Working Hours",
          'working': "Working",
          'insurance_number': "Insurance Number",
          'insurance_expires_on': "Insurance expires on",
          'number_of_employee': "Number of Employees",
          'edit_widget': "Edit Widget",
          'users': "Users",
          'teams': "Teams",
          'generate_code': "Generate code",
          'random_code_generator': "Random code generator",
          'generate': "Generate",
          'unauthorized_message':
              "We are signing you out as we found your account access from another device",
          'search_user': "Search  User",

          'date_of_birth': "Date of Birth",
          'post_code': "Post Code",
          'my_address': "My Address",
          'name': "Name",
          'utr': "UTR",
          'nin': "NIN",
          'name_on_account': "Name on Account",
          'bank_name': "Bank Name",
          'account_number': "Account Number",
          'sort_code': "Sort Code",
          'personal_info': "Personal Info",
          'general': "General",
          'tax_info': "Tax Info",
          'bank_details': "Bank Details",
          'select_all': "Select All",
          'unselect_all': "Unselect All",
          'create_new_team': "Create New Team",
          'edit_team': "Edit Team",
          'team_name': "Team Name",
          'select_supervisor': "Select Supervisor",
          'add_team_members': "Add team members",
          'select_team_members': "Select team members",
          'select': "Select",
          'add': "Add",
          'delete': "Delete",
          'edit': "Edit",
          'archive': "Archive",
          'un_archive': "UnArchive",
          'archived_teams': "Archived Teams",
          'create_code': "Create Code",
          'are_you_sure_you_want_to_delete': "Are you sure you want to delete?",
          'are_you_sure_you_want_to_approve':
              "Are you sure you want to approve?",
          'are_you_sure_you_want_to_reject': "Are you sure you want to reject?",
          'sub_contractor_details': "Subcontractor Details",
          'copy_code': "Copy Code",
          'copied_to_clip_board': "Copied to clipboard",
          'generate_password': "Generate Password",
          'again': "Again",
          'adjust_widgets': "Adjust Widgets",
          'all': "All",
          'create_new_shift': "Create new shift",
          'edit_shift': "Edit Shift",
          'shift_name': "Shift Name",
          'does_it_have_price_work': "Does it have price work?",
          'start_shift': "Start Shift",
          'end_shift': "End Shift",
          'start_break': "Start Break",
          'end_break': "End Break",
          'add_another_break': "Add another break",
          'select_days': "Select Days",
          'every_weekday': "Every Weekday",
          'weekend': "Weekend",
          'shift': "Shift",
          'breaks': "Breaks",
          'break': "Break",
          'shifts': "Shifts",
          'archived_shifts': "Archived Shifts",
          'billing_info': "Billing Info",
          'my_day_logs': "My Day Logs",
          'name_on_utr': "Name on UTR",
          'my_shift': "My Shift",
          'cancel': "Cancel",
          'timesheets': "Timesheets",
          'archived_timesheets': "Archived Timesheets",
          'edit_my_shift': "Edit My Shift",
          'reset': "Reset",
          'approve': "Approve",
          'reject': "Reject",
          'work_log': "Work Log",
          'my_account': "My Account",
          'switch_company': "Switch Company",
          'active': "Active",
          'are_you_sure_you_want_to_switch': "Are you sure you want to switch?",
          'delete_account': "Delete Account",
          'requested_note': "Requested Note",
          'approved_note': "Approved Note",
          'rejected_note': "Rejected Note",
          'companies': "Companies",
          'create_or_join': "Create or Join",
          'empty_note_error': "Please enter note",
          'add_project': "Add Project",
          'archived_projects': "Archived Projects",
          'update_project': "Update Project",
          'project_name': "Project Name",
          'select_teams': "Select Teams",
          'site_address': "Site Address",
          'budget': "Budget",
          'add_geofence': "Add Geofence",
          'add_addresses': "Add Addresses",
          'address': "Address",
          'project_code': "Project Code",
          'start_date': "Start Date",
          'end_date': "End Date:",
          'materials': "Materials",
          'price_work': "Price Work",
          'day_work': "Day Work",
          'total': "Total",
          'project_all': "Projects (All)",
          'search_shift': "Search Shift",
          'search_project': "Search Project",
          'search_task': "Search Task",
          'addresses': "Addresses",
          'archive_project': "Archive Project",
          'continue_shift': "Continue Shift",
          'admin': "Admin",
          'archived_address': "Archived Addresses",
          'change_progress': "Change Progress",
          'update_address': "Update Address",
          'add_address': "Add Address",
          'progress': "Progress",
          'address_postcode': "Address & Postcode",
          'no_billing_info_available': "No Billing Info Available",
          'add_billing_info': "Add Billing Info",
          'billing_information_submission_is_pending_for_approval':
              "Billing information submission is pending for approval",
          'rates': "Rates",
          'payslips': "Payslips",
          'Payment': "Payment",
          'invoice': "Invoice",
          'done': "Done",
          'this_billing_data_is_awaiting_for_approval':
              "This billing data is awaiting for approval",
          'do_you_want_to_leave_a_note': "Do you want to leave a note?",
          'enter_note': "Enter note",
          'billing_info_request': "Billing Info Request",
          'trade ': "Trade ",
          'net_per_day': "Net Per Day",
          'billing': "Billing",
          'health_info': "Health Info",
          'health_safety': "Health & Safety",
          'my_requests': "My Requests",
          'documents': "Documents",
          'my_leaves': "My Leaves",
          'digital_id': "Digital ID",
          'rent': "Rent",
          'history': "History",
          'search_post_code': "Search Post Code",
          'postcode_address': "Postcode or address",
          'addresses_found': "addresses found",
          'privacy_policy': "Privacy and Policy",
          'app_info': "App Info",
          'location': "Location",
          'project': "Project",
          'project_details': "Project Details",
          'warning': "Warning",
          'update_progress_warning_text_one': "You have to mark progress",
          'update_progress_warning_text_two': "to complete the task",
          'update_progress_warning_text_three':
              "Do you want to modify the progress",
          'msg_empty_before_after_Attachment':
              "Please select before and after attachment.",
          'push': "Push",
          'feed': "Feed",
          'announcement': "Announcement",
          'edit_rate': "Edit Rate",
          'join_company_date': "Join Company Date",
          'gross_per_day': "Gross Per Day",
          'cis': "CIS",
          'rate_history': "Rate History",
          'send': "Send",
          'trade': "Trade",
          'rate_request': "Rate Request",
          'note_min_length_error': "Note must be at least 60 characters",
          'note_max_length_error': "Note must not exceed 500 characters",
          'lock': "Lock",
          'mark_as_paid': "Mark as paid",
          'share': "Share",
          'view_amount': "View Amount",
          'history_logs': "History/Logs",
          'action': "Action",
          'add_timesheet': "Add Timesheet",
          'select_date': "Select Date",
          'error_wrong_time_selection':
              "Start Shift time must be less than End Shift time.",
// '': "",
          // '': "",
// '': "",
// '': "",
// '': "",
// '': "",
// '': "",
        },
        'hi_IN': {'login': 'Login'}
      };
}
