// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdLpTcvwOWzhK4maBtriznqiw5MwBNcZw',
    appId: '1:1046367619528:web:0052d384a1c66bd12418fd',
    messagingSenderId: '1046367619528',
    projectId: 'belcka-8f2cd',
    authDomain: 'belcka-8f2cd.firebaseapp.com',
    storageBucket: 'belcka-8f2cd.firebasestorage.app',
    measurementId: 'G-X39WLDVTHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdx8IqB5lGom3gN2ptumujHxONQpNFQHE',
    appId: '1:1046367619528:android:960eba8c1841f8f62418fd',
    messagingSenderId: '1046367619528',
    projectId: 'belcka-8f2cd',
    storageBucket: 'belcka-8f2cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeSO8kd_VZSStJhMGAijEKHNiqpj-ix4Y',
    appId: '1:1046367619528:ios:8c2d2a4eaae779e62418fd',
    messagingSenderId: '1046367619528',
    projectId: 'belcka-8f2cd',
    storageBucket: 'belcka-8f2cd.firebasestorage.app',
    iosBundleId: 'com.app.otmsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeSO8kd_VZSStJhMGAijEKHNiqpj-ix4Y',
    appId: '1:1046367619528:ios:8c2d2a4eaae779e62418fd',
    messagingSenderId: '1046367619528',
    projectId: 'belcka-8f2cd',
    storageBucket: 'belcka-8f2cd.firebasestorage.app',
    iosBundleId: 'com.app.otmsystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdLpTcvwOWzhK4maBtriznqiw5MwBNcZw',
    appId: '1:1046367619528:web:c596626b5bfd539f2418fd',
    messagingSenderId: '1046367619528',
    projectId: 'belcka-8f2cd',
    authDomain: 'belcka-8f2cd.firebaseapp.com',
    storageBucket: 'belcka-8f2cd.firebasestorage.app',
    measurementId: 'G-XB41PRH8YT',
  );

}